// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app.proto
// Protobuf Java Version: 4.29.3

package lampyris.futu.protocol.app;

public final class App {
  private App() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      App.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lampyris.futu.protocol.app.ReqHeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 客户端时间
     * </pre>
     *
     * <code>int64 clientTime = 1;</code>
     * @return The clientTime.
     */
    long getClientTime();

    /**
     * <pre>
     * 客户端是否置于前台
     * </pre>
     *
     * <code>bool isForeground = 2;</code>
     * @return The isForeground.
     */
    boolean getIsForeground();
  }
  /**
   * Protobuf type {@code lampyris.futu.protocol.app.ReqHeartBeat}
   */
  public static final class ReqHeartBeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lampyris.futu.protocol.app.ReqHeartBeat)
      ReqHeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ReqHeartBeat.class.getName());
    }
    // Use ReqHeartBeat.newBuilder() to construct.
    private ReqHeartBeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqHeartBeat() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ReqHeartBeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ReqHeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lampyris.futu.protocol.app.App.ReqHeartBeat.class, lampyris.futu.protocol.app.App.ReqHeartBeat.Builder.class);
    }

    public static final int CLIENTTIME_FIELD_NUMBER = 1;
    private long clientTime_ = 0L;
    /**
     * <pre>
     * 客户端时间
     * </pre>
     *
     * <code>int64 clientTime = 1;</code>
     * @return The clientTime.
     */
    @java.lang.Override
    public long getClientTime() {
      return clientTime_;
    }

    public static final int ISFOREGROUND_FIELD_NUMBER = 2;
    private boolean isForeground_ = false;
    /**
     * <pre>
     * 客户端是否置于前台
     * </pre>
     *
     * <code>bool isForeground = 2;</code>
     * @return The isForeground.
     */
    @java.lang.Override
    public boolean getIsForeground() {
      return isForeground_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientTime_ != 0L) {
        output.writeInt64(1, clientTime_);
      }
      if (isForeground_ != false) {
        output.writeBool(2, isForeground_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientTime_);
      }
      if (isForeground_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isForeground_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lampyris.futu.protocol.app.App.ReqHeartBeat)) {
        return super.equals(obj);
      }
      lampyris.futu.protocol.app.App.ReqHeartBeat other = (lampyris.futu.protocol.app.App.ReqHeartBeat) obj;

      if (getClientTime()
          != other.getClientTime()) return false;
      if (getIsForeground()
          != other.getIsForeground()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientTime());
      hash = (37 * hash) + ISFOREGROUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsForeground());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lampyris.futu.protocol.app.App.ReqHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lampyris.futu.protocol.app.App.ReqHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lampyris.futu.protocol.app.ReqHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lampyris.futu.protocol.app.ReqHeartBeat)
        lampyris.futu.protocol.app.App.ReqHeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ReqHeartBeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ReqHeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lampyris.futu.protocol.app.App.ReqHeartBeat.class, lampyris.futu.protocol.app.App.ReqHeartBeat.Builder.class);
      }

      // Construct using lampyris.futu.protocol.app.App.ReqHeartBeat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        clientTime_ = 0L;
        isForeground_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ReqHeartBeat_descriptor;
      }

      @java.lang.Override
      public lampyris.futu.protocol.app.App.ReqHeartBeat getDefaultInstanceForType() {
        return lampyris.futu.protocol.app.App.ReqHeartBeat.getDefaultInstance();
      }

      @java.lang.Override
      public lampyris.futu.protocol.app.App.ReqHeartBeat build() {
        lampyris.futu.protocol.app.App.ReqHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lampyris.futu.protocol.app.App.ReqHeartBeat buildPartial() {
        lampyris.futu.protocol.app.App.ReqHeartBeat result = new lampyris.futu.protocol.app.App.ReqHeartBeat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lampyris.futu.protocol.app.App.ReqHeartBeat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.clientTime_ = clientTime_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isForeground_ = isForeground_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lampyris.futu.protocol.app.App.ReqHeartBeat) {
          return mergeFrom((lampyris.futu.protocol.app.App.ReqHeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lampyris.futu.protocol.app.App.ReqHeartBeat other) {
        if (other == lampyris.futu.protocol.app.App.ReqHeartBeat.getDefaultInstance()) return this;
        if (other.getClientTime() != 0L) {
          setClientTime(other.getClientTime());
        }
        if (other.getIsForeground() != false) {
          setIsForeground(other.getIsForeground());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                clientTime_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                isForeground_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long clientTime_ ;
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       * @return The clientTime.
       */
      @java.lang.Override
      public long getClientTime() {
        return clientTime_;
      }
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       * @param value The clientTime to set.
       * @return This builder for chaining.
       */
      public Builder setClientTime(long value) {

        clientTime_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端时间
       * </pre>
       *
       * <code>int64 clientTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientTime_ = 0L;
        onChanged();
        return this;
      }

      private boolean isForeground_ ;
      /**
       * <pre>
       * 客户端是否置于前台
       * </pre>
       *
       * <code>bool isForeground = 2;</code>
       * @return The isForeground.
       */
      @java.lang.Override
      public boolean getIsForeground() {
        return isForeground_;
      }
      /**
       * <pre>
       * 客户端是否置于前台
       * </pre>
       *
       * <code>bool isForeground = 2;</code>
       * @param value The isForeground to set.
       * @return This builder for chaining.
       */
      public Builder setIsForeground(boolean value) {

        isForeground_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 客户端是否置于前台
       * </pre>
       *
       * <code>bool isForeground = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsForeground() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isForeground_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lampyris.futu.protocol.app.ReqHeartBeat)
    }

    // @@protoc_insertion_point(class_scope:lampyris.futu.protocol.app.ReqHeartBeat)
    private static final lampyris.futu.protocol.app.App.ReqHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lampyris.futu.protocol.app.App.ReqHeartBeat();
    }

    public static lampyris.futu.protocol.app.App.ReqHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqHeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<ReqHeartBeat>() {
      @java.lang.Override
      public ReqHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqHeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqHeartBeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lampyris.futu.protocol.app.App.ReqHeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResHeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lampyris.futu.protocol.app.ResHeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务端时间
     * </pre>
     *
     * <code>int64 serverTime = 1;</code>
     * @return The serverTime.
     */
    long getServerTime();
  }
  /**
   * <pre>
   * 响应-服务端发送心跳包
   * </pre>
   *
   * Protobuf type {@code lampyris.futu.protocol.app.ResHeartBeat}
   */
  public static final class ResHeartBeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lampyris.futu.protocol.app.ResHeartBeat)
      ResHeartBeatOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ResHeartBeat.class.getName());
    }
    // Use ResHeartBeat.newBuilder() to construct.
    private ResHeartBeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResHeartBeat() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ResHeartBeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ResHeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lampyris.futu.protocol.app.App.ResHeartBeat.class, lampyris.futu.protocol.app.App.ResHeartBeat.Builder.class);
    }

    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private long serverTime_ = 0L;
    /**
     * <pre>
     * 服务端时间
     * </pre>
     *
     * <code>int64 serverTime = 1;</code>
     * @return The serverTime.
     */
    @java.lang.Override
    public long getServerTime() {
      return serverTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverTime_ != 0L) {
        output.writeInt64(1, serverTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, serverTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lampyris.futu.protocol.app.App.ResHeartBeat)) {
        return super.equals(obj);
      }
      lampyris.futu.protocol.app.App.ResHeartBeat other = (lampyris.futu.protocol.app.App.ResHeartBeat) obj;

      if (getServerTime()
          != other.getServerTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lampyris.futu.protocol.app.App.ResHeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lampyris.futu.protocol.app.App.ResHeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lampyris.futu.protocol.app.App.ResHeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lampyris.futu.protocol.app.App.ResHeartBeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应-服务端发送心跳包
     * </pre>
     *
     * Protobuf type {@code lampyris.futu.protocol.app.ResHeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lampyris.futu.protocol.app.ResHeartBeat)
        lampyris.futu.protocol.app.App.ResHeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ResHeartBeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ResHeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lampyris.futu.protocol.app.App.ResHeartBeat.class, lampyris.futu.protocol.app.App.ResHeartBeat.Builder.class);
      }

      // Construct using lampyris.futu.protocol.app.App.ResHeartBeat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serverTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lampyris.futu.protocol.app.App.internal_static_lampyris_futu_protocol_app_ResHeartBeat_descriptor;
      }

      @java.lang.Override
      public lampyris.futu.protocol.app.App.ResHeartBeat getDefaultInstanceForType() {
        return lampyris.futu.protocol.app.App.ResHeartBeat.getDefaultInstance();
      }

      @java.lang.Override
      public lampyris.futu.protocol.app.App.ResHeartBeat build() {
        lampyris.futu.protocol.app.App.ResHeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lampyris.futu.protocol.app.App.ResHeartBeat buildPartial() {
        lampyris.futu.protocol.app.App.ResHeartBeat result = new lampyris.futu.protocol.app.App.ResHeartBeat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lampyris.futu.protocol.app.App.ResHeartBeat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverTime_ = serverTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lampyris.futu.protocol.app.App.ResHeartBeat) {
          return mergeFrom((lampyris.futu.protocol.app.App.ResHeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lampyris.futu.protocol.app.App.ResHeartBeat other) {
        if (other == lampyris.futu.protocol.app.App.ResHeartBeat.getDefaultInstance()) return this;
        if (other.getServerTime() != 0L) {
          setServerTime(other.getServerTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                serverTime_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long serverTime_ ;
      /**
       * <pre>
       * 服务端时间
       * </pre>
       *
       * <code>int64 serverTime = 1;</code>
       * @return The serverTime.
       */
      @java.lang.Override
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <pre>
       * 服务端时间
       * </pre>
       *
       * <code>int64 serverTime = 1;</code>
       * @param value The serverTime to set.
       * @return This builder for chaining.
       */
      public Builder setServerTime(long value) {

        serverTime_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务端时间
       * </pre>
       *
       * <code>int64 serverTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lampyris.futu.protocol.app.ResHeartBeat)
    }

    // @@protoc_insertion_point(class_scope:lampyris.futu.protocol.app.ResHeartBeat)
    private static final lampyris.futu.protocol.app.App.ResHeartBeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lampyris.futu.protocol.app.App.ResHeartBeat();
    }

    public static lampyris.futu.protocol.app.App.ResHeartBeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResHeartBeat>
        PARSER = new com.google.protobuf.AbstractParser<ResHeartBeat>() {
      @java.lang.Override
      public ResHeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResHeartBeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResHeartBeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lampyris.futu.protocol.app.App.ResHeartBeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lampyris_futu_protocol_app_ReqHeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lampyris_futu_protocol_app_ReqHeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lampyris_futu_protocol_app_ResHeartBeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lampyris_futu_protocol_app_ResHeartBeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapp.proto\022\032lampyris.futu.protocol.app\"" +
      "8\n\014ReqHeartBeat\022\022\n\nclientTime\030\001 \001(\003\022\024\n\014i" +
      "sForeground\030\002 \001(\010\"\"\n\014ResHeartBeat\022\022\n\nser" +
      "verTime\030\001 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lampyris_futu_protocol_app_ReqHeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lampyris_futu_protocol_app_ReqHeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lampyris_futu_protocol_app_ReqHeartBeat_descriptor,
        new java.lang.String[] { "ClientTime", "IsForeground", });
    internal_static_lampyris_futu_protocol_app_ResHeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lampyris_futu_protocol_app_ResHeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lampyris_futu_protocol_app_ResHeartBeat_descriptor,
        new java.lang.String[] { "ServerTime", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
