// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app.proto
// Protobuf C++ Version: 5.29.3

#include "app.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace lampyris {
namespace crypto {
namespace protocol {
namespace app {

inline constexpr ResNotice::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::lampyris::crypto::protocol::app::NoticeType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResNotice::ResNotice(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResNoticeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResNoticeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResNoticeDefaultTypeInternal() {}
  union {
    ResNotice _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResNoticeDefaultTypeInternal _ResNotice_default_instance_;

inline constexpr ResLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : errormessage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResLogin::ResLogin(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResLoginDefaultTypeInternal() {}
  union {
    ResLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResLoginDefaultTypeInternal _ResLogin_default_instance_;

inline constexpr ResHeartBeat::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : servertime_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResHeartBeat::ResHeartBeat(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResHeartBeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResHeartBeatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResHeartBeatDefaultTypeInternal() {}
  union {
    ResHeartBeat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResHeartBeatDefaultTypeInternal _ResHeartBeat_default_instance_;

inline constexpr ReqUploadAppBehaviour::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{::int64_t{0}},
        isenter_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReqUploadAppBehaviour::ReqUploadAppBehaviour(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReqUploadAppBehaviourDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqUploadAppBehaviourDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqUploadAppBehaviourDefaultTypeInternal() {}
  union {
    ReqUploadAppBehaviour _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqUploadAppBehaviourDefaultTypeInternal _ReqUploadAppBehaviour_default_instance_;

inline constexpr ReqLogout::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : devicemac_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReqLogout::ReqLogout(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReqLogoutDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqLogoutDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqLogoutDefaultTypeInternal() {}
  union {
    ReqLogout _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqLogoutDefaultTypeInternal _ReqLogout_default_instance_;

inline constexpr ReqLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : devicemac_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        devicename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReqLogin::ReqLogin(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReqLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqLoginDefaultTypeInternal() {}
  union {
    ReqLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqLoginDefaultTypeInternal _ReqLogin_default_instance_;

inline constexpr ReqHeartBeat::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : clienttime_{::int64_t{0}},
        isforeground_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReqHeartBeat::ReqHeartBeat(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReqHeartBeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqHeartBeatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqHeartBeatDefaultTypeInternal() {}
  union {
    ReqHeartBeat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqHeartBeatDefaultTypeInternal _ReqHeartBeat_default_instance_;
}  // namespace app
}  // namespace protocol
}  // namespace crypto
}  // namespace lampyris
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_app_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_app_2eproto = nullptr;
const ::uint32_t
    TableStruct_app_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqLogin, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqLogin, _impl_.devicemac_),
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqLogin, _impl_.devicename_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqLogout, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqLogout, _impl_.devicemac_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ResLogin, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ResLogin, _impl_.errormessage_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqHeartBeat, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqHeartBeat, _impl_.clienttime_),
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqHeartBeat, _impl_.isforeground_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ResHeartBeat, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ResHeartBeat, _impl_.servertime_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqUploadAppBehaviour, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqUploadAppBehaviour, _impl_.symbol_),
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqUploadAppBehaviour, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ReqUploadAppBehaviour, _impl_.isenter_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ResNotice, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ResNotice, _impl_.content_),
        PROTOBUF_FIELD_OFFSET(::lampyris::crypto::protocol::app::ResNotice, _impl_.type_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::lampyris::crypto::protocol::app::ReqLogin)},
        {10, -1, -1, sizeof(::lampyris::crypto::protocol::app::ReqLogout)},
        {19, -1, -1, sizeof(::lampyris::crypto::protocol::app::ResLogin)},
        {28, -1, -1, sizeof(::lampyris::crypto::protocol::app::ReqHeartBeat)},
        {38, -1, -1, sizeof(::lampyris::crypto::protocol::app::ResHeartBeat)},
        {47, -1, -1, sizeof(::lampyris::crypto::protocol::app::ReqUploadAppBehaviour)},
        {58, -1, -1, sizeof(::lampyris::crypto::protocol::app::ResNotice)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::lampyris::crypto::protocol::app::_ReqLogin_default_instance_._instance,
    &::lampyris::crypto::protocol::app::_ReqLogout_default_instance_._instance,
    &::lampyris::crypto::protocol::app::_ResLogin_default_instance_._instance,
    &::lampyris::crypto::protocol::app::_ReqHeartBeat_default_instance_._instance,
    &::lampyris::crypto::protocol::app::_ResHeartBeat_default_instance_._instance,
    &::lampyris::crypto::protocol::app::_ReqUploadAppBehaviour_default_instance_._instance,
    &::lampyris::crypto::protocol::app::_ResNotice_default_instance_._instance,
};
const char descriptor_table_protodef_app_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tapp.proto\022\034lampyris.crypto.protocol.ap"
    "p\"1\n\010ReqLogin\022\021\n\tdeviceMAC\030\001 \001(\t\022\022\n\ndevi"
    "ceName\030\002 \001(\t\"\036\n\tReqLogout\022\021\n\tdeviceMAC\030\001"
    " \001(\t\" \n\010ResLogin\022\024\n\014errorMessage\030\001 \001(\t\"8"
    "\n\014ReqHeartBeat\022\022\n\nclientTime\030\001 \001(\003\022\024\n\014is"
    "Foreground\030\002 \001(\010\"\"\n\014ResHeartBeat\022\022\n\nserv"
    "erTime\030\001 \001(\003\"K\n\025ReqUploadAppBehaviour\022\016\n"
    "\006symbol\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\022\017\n\007isEn"
    "ter\030\003 \001(\010\"T\n\tResNotice\022\017\n\007content\030\001 \001(\t\022"
    "6\n\004type\030\002 \001(\0162(.lampyris.crypto.protocol"
    ".app.NoticeType*(\n\nNoticeType\022\t\n\005Toast\020\000"
    "\022\017\n\013AlertDialog\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_app_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_app_2eproto = {
    false,
    false,
    465,
    descriptor_table_protodef_app_2eproto,
    "app.proto",
    &descriptor_table_app_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_app_2eproto::offsets,
    file_level_enum_descriptors_app_2eproto,
    file_level_service_descriptors_app_2eproto,
};
namespace lampyris {
namespace crypto {
namespace protocol {
namespace app {
const ::google::protobuf::EnumDescriptor* NoticeType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_app_2eproto);
  return file_level_enum_descriptors_app_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t NoticeType_internal_data_[] = {
    131072u, 0u, };
bool NoticeType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class ReqLogin::_Internal {
 public:
};

ReqLogin::ReqLogin(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lampyris.crypto.protocol.app.ReqLogin)
}
inline PROTOBUF_NDEBUG_INLINE ReqLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lampyris::crypto::protocol::app::ReqLogin& from_msg)
      : devicemac_(arena, from.devicemac_),
        devicename_(arena, from.devicename_),
        _cached_size_{0} {}

ReqLogin::ReqLogin(
    ::google::protobuf::Arena* arena,
    const ReqLogin& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReqLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:lampyris.crypto.protocol.app.ReqLogin)
}
inline PROTOBUF_NDEBUG_INLINE ReqLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : devicemac_(arena),
        devicename_(arena),
        _cached_size_{0} {}

inline void ReqLogin::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ReqLogin::~ReqLogin() {
  // @@protoc_insertion_point(destructor:lampyris.crypto.protocol.app.ReqLogin)
  SharedDtor(*this);
}
inline void ReqLogin::SharedDtor(MessageLite& self) {
  ReqLogin& this_ = static_cast<ReqLogin&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.devicemac_.Destroy();
  this_._impl_.devicename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ReqLogin::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReqLogin(arena);
}
constexpr auto ReqLogin::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReqLogin),
                                            alignof(ReqLogin));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReqLogin::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReqLogin_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReqLogin::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ReqLogin>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReqLogin::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ReqLogin>(), &ReqLogin::ByteSizeLong,
            &ReqLogin::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_._cached_size_),
        false,
    },
    &ReqLogin::kDescriptorMethods,
    &descriptor_table_app_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReqLogin::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 65, 2> ReqLogin::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lampyris::crypto::protocol::app::ReqLogin>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string deviceName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.devicename_)}},
    // string deviceMAC = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.devicemac_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string deviceMAC = 1;
    {PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.devicemac_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string deviceName = 2;
    {PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.devicename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\11\12\0\0\0\0\0"
    "lampyris.crypto.protocol.app.ReqLogin"
    "deviceMAC"
    "deviceName"
  }},
};

PROTOBUF_NOINLINE void ReqLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:lampyris.crypto.protocol.app.ReqLogin)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.devicemac_.ClearToEmpty();
  _impl_.devicename_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ReqLogin::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ReqLogin& this_ = static_cast<const ReqLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ReqLogin::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ReqLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:lampyris.crypto.protocol.app.ReqLogin)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string deviceMAC = 1;
          if (!this_._internal_devicemac().empty()) {
            const std::string& _s = this_._internal_devicemac();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lampyris.crypto.protocol.app.ReqLogin.deviceMAC");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string deviceName = 2;
          if (!this_._internal_devicename().empty()) {
            const std::string& _s = this_._internal_devicename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lampyris.crypto.protocol.app.ReqLogin.deviceName");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:lampyris.crypto.protocol.app.ReqLogin)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ReqLogin::ByteSizeLong(const MessageLite& base) {
          const ReqLogin& this_ = static_cast<const ReqLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ReqLogin::ByteSizeLong() const {
          const ReqLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:lampyris.crypto.protocol.app.ReqLogin)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string deviceMAC = 1;
            if (!this_._internal_devicemac().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_devicemac());
            }
            // string deviceName = 2;
            if (!this_._internal_devicename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_devicename());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ReqLogin::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReqLogin*>(&to_msg);
  auto& from = static_cast<const ReqLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lampyris.crypto.protocol.app.ReqLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_devicemac().empty()) {
    _this->_internal_set_devicemac(from._internal_devicemac());
  }
  if (!from._internal_devicename().empty()) {
    _this->_internal_set_devicename(from._internal_devicename());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReqLogin::CopyFrom(const ReqLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lampyris.crypto.protocol.app.ReqLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReqLogin::InternalSwap(ReqLogin* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.devicemac_, &other->_impl_.devicemac_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.devicename_, &other->_impl_.devicename_, arena);
}

::google::protobuf::Metadata ReqLogin::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReqLogout::_Internal {
 public:
};

ReqLogout::ReqLogout(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lampyris.crypto.protocol.app.ReqLogout)
}
inline PROTOBUF_NDEBUG_INLINE ReqLogout::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lampyris::crypto::protocol::app::ReqLogout& from_msg)
      : devicemac_(arena, from.devicemac_),
        _cached_size_{0} {}

ReqLogout::ReqLogout(
    ::google::protobuf::Arena* arena,
    const ReqLogout& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReqLogout* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:lampyris.crypto.protocol.app.ReqLogout)
}
inline PROTOBUF_NDEBUG_INLINE ReqLogout::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : devicemac_(arena),
        _cached_size_{0} {}

inline void ReqLogout::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ReqLogout::~ReqLogout() {
  // @@protoc_insertion_point(destructor:lampyris.crypto.protocol.app.ReqLogout)
  SharedDtor(*this);
}
inline void ReqLogout::SharedDtor(MessageLite& self) {
  ReqLogout& this_ = static_cast<ReqLogout&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.devicemac_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ReqLogout::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReqLogout(arena);
}
constexpr auto ReqLogout::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReqLogout),
                                            alignof(ReqLogout));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReqLogout::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReqLogout_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReqLogout::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ReqLogout>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReqLogout::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ReqLogout>(), &ReqLogout::ByteSizeLong,
            &ReqLogout::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReqLogout, _impl_._cached_size_),
        false,
    },
    &ReqLogout::kDescriptorMethods,
    &descriptor_table_app_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReqLogout::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 56, 2> ReqLogout::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lampyris::crypto::protocol::app::ReqLogout>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string deviceMAC = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ReqLogout, _impl_.devicemac_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string deviceMAC = 1;
    {PROTOBUF_FIELD_OFFSET(ReqLogout, _impl_.devicemac_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\46\11\0\0\0\0\0\0"
    "lampyris.crypto.protocol.app.ReqLogout"
    "deviceMAC"
  }},
};

PROTOBUF_NOINLINE void ReqLogout::Clear() {
// @@protoc_insertion_point(message_clear_start:lampyris.crypto.protocol.app.ReqLogout)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.devicemac_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ReqLogout::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ReqLogout& this_ = static_cast<const ReqLogout&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ReqLogout::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ReqLogout& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:lampyris.crypto.protocol.app.ReqLogout)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string deviceMAC = 1;
          if (!this_._internal_devicemac().empty()) {
            const std::string& _s = this_._internal_devicemac();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lampyris.crypto.protocol.app.ReqLogout.deviceMAC");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:lampyris.crypto.protocol.app.ReqLogout)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ReqLogout::ByteSizeLong(const MessageLite& base) {
          const ReqLogout& this_ = static_cast<const ReqLogout&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ReqLogout::ByteSizeLong() const {
          const ReqLogout& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:lampyris.crypto.protocol.app.ReqLogout)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string deviceMAC = 1;
            if (!this_._internal_devicemac().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_devicemac());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ReqLogout::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReqLogout*>(&to_msg);
  auto& from = static_cast<const ReqLogout&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lampyris.crypto.protocol.app.ReqLogout)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_devicemac().empty()) {
    _this->_internal_set_devicemac(from._internal_devicemac());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReqLogout::CopyFrom(const ReqLogout& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lampyris.crypto.protocol.app.ReqLogout)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReqLogout::InternalSwap(ReqLogout* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.devicemac_, &other->_impl_.devicemac_, arena);
}

::google::protobuf::Metadata ReqLogout::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResLogin::_Internal {
 public:
};

ResLogin::ResLogin(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lampyris.crypto.protocol.app.ResLogin)
}
inline PROTOBUF_NDEBUG_INLINE ResLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lampyris::crypto::protocol::app::ResLogin& from_msg)
      : errormessage_(arena, from.errormessage_),
        _cached_size_{0} {}

ResLogin::ResLogin(
    ::google::protobuf::Arena* arena,
    const ResLogin& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:lampyris.crypto.protocol.app.ResLogin)
}
inline PROTOBUF_NDEBUG_INLINE ResLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : errormessage_(arena),
        _cached_size_{0} {}

inline void ResLogin::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ResLogin::~ResLogin() {
  // @@protoc_insertion_point(destructor:lampyris.crypto.protocol.app.ResLogin)
  SharedDtor(*this);
}
inline void ResLogin::SharedDtor(MessageLite& self) {
  ResLogin& this_ = static_cast<ResLogin&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.errormessage_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ResLogin::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ResLogin(arena);
}
constexpr auto ResLogin::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResLogin),
                                            alignof(ResLogin));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ResLogin::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ResLogin_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ResLogin::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ResLogin>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ResLogin::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ResLogin>(), &ResLogin::ByteSizeLong,
            &ResLogin::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ResLogin, _impl_._cached_size_),
        false,
    },
    &ResLogin::kDescriptorMethods,
    &descriptor_table_app_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ResLogin::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 58, 2> ResLogin::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lampyris::crypto::protocol::app::ResLogin>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string errorMessage = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ResLogin, _impl_.errormessage_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string errorMessage = 1;
    {PROTOBUF_FIELD_OFFSET(ResLogin, _impl_.errormessage_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\14\0\0\0\0\0\0"
    "lampyris.crypto.protocol.app.ResLogin"
    "errorMessage"
  }},
};

PROTOBUF_NOINLINE void ResLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:lampyris.crypto.protocol.app.ResLogin)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.errormessage_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ResLogin::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ResLogin& this_ = static_cast<const ResLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ResLogin::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ResLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:lampyris.crypto.protocol.app.ResLogin)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string errorMessage = 1;
          if (!this_._internal_errormessage().empty()) {
            const std::string& _s = this_._internal_errormessage();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lampyris.crypto.protocol.app.ResLogin.errorMessage");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:lampyris.crypto.protocol.app.ResLogin)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ResLogin::ByteSizeLong(const MessageLite& base) {
          const ResLogin& this_ = static_cast<const ResLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ResLogin::ByteSizeLong() const {
          const ResLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:lampyris.crypto.protocol.app.ResLogin)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string errorMessage = 1;
            if (!this_._internal_errormessage().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_errormessage());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ResLogin::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResLogin*>(&to_msg);
  auto& from = static_cast<const ResLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lampyris.crypto.protocol.app.ResLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_errormessage().empty()) {
    _this->_internal_set_errormessage(from._internal_errormessage());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResLogin::CopyFrom(const ResLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lampyris.crypto.protocol.app.ResLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResLogin::InternalSwap(ResLogin* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.errormessage_, &other->_impl_.errormessage_, arena);
}

::google::protobuf::Metadata ResLogin::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReqHeartBeat::_Internal {
 public:
};

ReqHeartBeat::ReqHeartBeat(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lampyris.crypto.protocol.app.ReqHeartBeat)
}
ReqHeartBeat::ReqHeartBeat(
    ::google::protobuf::Arena* arena, const ReqHeartBeat& from)
    : ReqHeartBeat(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ReqHeartBeat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ReqHeartBeat::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, clienttime_),
           0,
           offsetof(Impl_, isforeground_) -
               offsetof(Impl_, clienttime_) +
               sizeof(Impl_::isforeground_));
}
ReqHeartBeat::~ReqHeartBeat() {
  // @@protoc_insertion_point(destructor:lampyris.crypto.protocol.app.ReqHeartBeat)
  SharedDtor(*this);
}
inline void ReqHeartBeat::SharedDtor(MessageLite& self) {
  ReqHeartBeat& this_ = static_cast<ReqHeartBeat&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ReqHeartBeat::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReqHeartBeat(arena);
}
constexpr auto ReqHeartBeat::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ReqHeartBeat),
                                            alignof(ReqHeartBeat));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReqHeartBeat::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReqHeartBeat_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReqHeartBeat::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ReqHeartBeat>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReqHeartBeat::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ReqHeartBeat>(), &ReqHeartBeat::ByteSizeLong,
            &ReqHeartBeat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReqHeartBeat, _impl_._cached_size_),
        false,
    },
    &ReqHeartBeat::kDescriptorMethods,
    &descriptor_table_app_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReqHeartBeat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ReqHeartBeat::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lampyris::crypto::protocol::app::ReqHeartBeat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool isForeground = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ReqHeartBeat, _impl_.isforeground_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ReqHeartBeat, _impl_.isforeground_)}},
    // int64 clientTime = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ReqHeartBeat, _impl_.clienttime_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ReqHeartBeat, _impl_.clienttime_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 clientTime = 1;
    {PROTOBUF_FIELD_OFFSET(ReqHeartBeat, _impl_.clienttime_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bool isForeground = 2;
    {PROTOBUF_FIELD_OFFSET(ReqHeartBeat, _impl_.isforeground_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ReqHeartBeat::Clear() {
// @@protoc_insertion_point(message_clear_start:lampyris.crypto.protocol.app.ReqHeartBeat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.clienttime_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.isforeground_) -
      reinterpret_cast<char*>(&_impl_.clienttime_)) + sizeof(_impl_.isforeground_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ReqHeartBeat::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ReqHeartBeat& this_ = static_cast<const ReqHeartBeat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ReqHeartBeat::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ReqHeartBeat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:lampyris.crypto.protocol.app.ReqHeartBeat)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 clientTime = 1;
          if (this_._internal_clienttime() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_clienttime(), target);
          }

          // bool isForeground = 2;
          if (this_._internal_isforeground() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_isforeground(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:lampyris.crypto.protocol.app.ReqHeartBeat)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ReqHeartBeat::ByteSizeLong(const MessageLite& base) {
          const ReqHeartBeat& this_ = static_cast<const ReqHeartBeat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ReqHeartBeat::ByteSizeLong() const {
          const ReqHeartBeat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:lampyris.crypto.protocol.app.ReqHeartBeat)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int64 clientTime = 1;
            if (this_._internal_clienttime() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_clienttime());
            }
            // bool isForeground = 2;
            if (this_._internal_isforeground() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ReqHeartBeat::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReqHeartBeat*>(&to_msg);
  auto& from = static_cast<const ReqHeartBeat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lampyris.crypto.protocol.app.ReqHeartBeat)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_clienttime() != 0) {
    _this->_impl_.clienttime_ = from._impl_.clienttime_;
  }
  if (from._internal_isforeground() != 0) {
    _this->_impl_.isforeground_ = from._impl_.isforeground_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReqHeartBeat::CopyFrom(const ReqHeartBeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lampyris.crypto.protocol.app.ReqHeartBeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReqHeartBeat::InternalSwap(ReqHeartBeat* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReqHeartBeat, _impl_.isforeground_)
      + sizeof(ReqHeartBeat::_impl_.isforeground_)
      - PROTOBUF_FIELD_OFFSET(ReqHeartBeat, _impl_.clienttime_)>(
          reinterpret_cast<char*>(&_impl_.clienttime_),
          reinterpret_cast<char*>(&other->_impl_.clienttime_));
}

::google::protobuf::Metadata ReqHeartBeat::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResHeartBeat::_Internal {
 public:
};

ResHeartBeat::ResHeartBeat(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lampyris.crypto.protocol.app.ResHeartBeat)
}
ResHeartBeat::ResHeartBeat(
    ::google::protobuf::Arena* arena, const ResHeartBeat& from)
    : ResHeartBeat(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ResHeartBeat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ResHeartBeat::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.servertime_ = {};
}
ResHeartBeat::~ResHeartBeat() {
  // @@protoc_insertion_point(destructor:lampyris.crypto.protocol.app.ResHeartBeat)
  SharedDtor(*this);
}
inline void ResHeartBeat::SharedDtor(MessageLite& self) {
  ResHeartBeat& this_ = static_cast<ResHeartBeat&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ResHeartBeat::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ResHeartBeat(arena);
}
constexpr auto ResHeartBeat::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ResHeartBeat),
                                            alignof(ResHeartBeat));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ResHeartBeat::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ResHeartBeat_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ResHeartBeat::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ResHeartBeat>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ResHeartBeat::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ResHeartBeat>(), &ResHeartBeat::ByteSizeLong,
            &ResHeartBeat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ResHeartBeat, _impl_._cached_size_),
        false,
    },
    &ResHeartBeat::kDescriptorMethods,
    &descriptor_table_app_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ResHeartBeat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ResHeartBeat::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lampyris::crypto::protocol::app::ResHeartBeat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 serverTime = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ResHeartBeat, _impl_.servertime_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ResHeartBeat, _impl_.servertime_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 serverTime = 1;
    {PROTOBUF_FIELD_OFFSET(ResHeartBeat, _impl_.servertime_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ResHeartBeat::Clear() {
// @@protoc_insertion_point(message_clear_start:lampyris.crypto.protocol.app.ResHeartBeat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.servertime_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ResHeartBeat::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ResHeartBeat& this_ = static_cast<const ResHeartBeat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ResHeartBeat::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ResHeartBeat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:lampyris.crypto.protocol.app.ResHeartBeat)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 serverTime = 1;
          if (this_._internal_servertime() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_servertime(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:lampyris.crypto.protocol.app.ResHeartBeat)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ResHeartBeat::ByteSizeLong(const MessageLite& base) {
          const ResHeartBeat& this_ = static_cast<const ResHeartBeat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ResHeartBeat::ByteSizeLong() const {
          const ResHeartBeat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:lampyris.crypto.protocol.app.ResHeartBeat)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int64 serverTime = 1;
            if (this_._internal_servertime() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_servertime());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ResHeartBeat::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResHeartBeat*>(&to_msg);
  auto& from = static_cast<const ResHeartBeat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lampyris.crypto.protocol.app.ResHeartBeat)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_servertime() != 0) {
    _this->_impl_.servertime_ = from._impl_.servertime_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResHeartBeat::CopyFrom(const ResHeartBeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lampyris.crypto.protocol.app.ResHeartBeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResHeartBeat::InternalSwap(ResHeartBeat* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.servertime_, other->_impl_.servertime_);
}

::google::protobuf::Metadata ResHeartBeat::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReqUploadAppBehaviour::_Internal {
 public:
};

ReqUploadAppBehaviour::ReqUploadAppBehaviour(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
}
inline PROTOBUF_NDEBUG_INLINE ReqUploadAppBehaviour::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lampyris::crypto::protocol::app::ReqUploadAppBehaviour& from_msg)
      : symbol_(arena, from.symbol_),
        _cached_size_{0} {}

ReqUploadAppBehaviour::ReqUploadAppBehaviour(
    ::google::protobuf::Arena* arena,
    const ReqUploadAppBehaviour& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReqUploadAppBehaviour* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, isenter_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::isenter_));

  // @@protoc_insertion_point(copy_constructor:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
}
inline PROTOBUF_NDEBUG_INLINE ReqUploadAppBehaviour::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : symbol_(arena),
        _cached_size_{0} {}

inline void ReqUploadAppBehaviour::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, isenter_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::isenter_));
}
ReqUploadAppBehaviour::~ReqUploadAppBehaviour() {
  // @@protoc_insertion_point(destructor:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
  SharedDtor(*this);
}
inline void ReqUploadAppBehaviour::SharedDtor(MessageLite& self) {
  ReqUploadAppBehaviour& this_ = static_cast<ReqUploadAppBehaviour&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.symbol_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ReqUploadAppBehaviour::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReqUploadAppBehaviour(arena);
}
constexpr auto ReqUploadAppBehaviour::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReqUploadAppBehaviour),
                                            alignof(ReqUploadAppBehaviour));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReqUploadAppBehaviour::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReqUploadAppBehaviour_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReqUploadAppBehaviour::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ReqUploadAppBehaviour>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReqUploadAppBehaviour::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ReqUploadAppBehaviour>(), &ReqUploadAppBehaviour::ByteSizeLong,
            &ReqUploadAppBehaviour::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_._cached_size_),
        false,
    },
    &ReqUploadAppBehaviour::kDescriptorMethods,
    &descriptor_table_app_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReqUploadAppBehaviour::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 65, 2> ReqUploadAppBehaviour::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lampyris::crypto::protocol::app::ReqUploadAppBehaviour>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string symbol = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_.symbol_)}},
    // int64 timestamp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ReqUploadAppBehaviour, _impl_.timestamp_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_.timestamp_)}},
    // bool isEnter = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ReqUploadAppBehaviour, _impl_.isenter_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_.isenter_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string symbol = 1;
    {PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_.symbol_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bool isEnter = 3;
    {PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_.isenter_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\62\6\0\0\0\0\0\0"
    "lampyris.crypto.protocol.app.ReqUploadAppBehaviour"
    "symbol"
  }},
};

PROTOBUF_NOINLINE void ReqUploadAppBehaviour::Clear() {
// @@protoc_insertion_point(message_clear_start:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.symbol_.ClearToEmpty();
  ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.isenter_) -
      reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.isenter_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ReqUploadAppBehaviour::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ReqUploadAppBehaviour& this_ = static_cast<const ReqUploadAppBehaviour&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ReqUploadAppBehaviour::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ReqUploadAppBehaviour& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string symbol = 1;
          if (!this_._internal_symbol().empty()) {
            const std::string& _s = this_._internal_symbol();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lampyris.crypto.protocol.app.ReqUploadAppBehaviour.symbol");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int64 timestamp = 2;
          if (this_._internal_timestamp() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_timestamp(), target);
          }

          // bool isEnter = 3;
          if (this_._internal_isenter() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_isenter(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ReqUploadAppBehaviour::ByteSizeLong(const MessageLite& base) {
          const ReqUploadAppBehaviour& this_ = static_cast<const ReqUploadAppBehaviour&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ReqUploadAppBehaviour::ByteSizeLong() const {
          const ReqUploadAppBehaviour& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string symbol = 1;
            if (!this_._internal_symbol().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_symbol());
            }
            // int64 timestamp = 2;
            if (this_._internal_timestamp() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_timestamp());
            }
            // bool isEnter = 3;
            if (this_._internal_isenter() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ReqUploadAppBehaviour::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReqUploadAppBehaviour*>(&to_msg);
  auto& from = static_cast<const ReqUploadAppBehaviour&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_symbol().empty()) {
    _this->_internal_set_symbol(from._internal_symbol());
  }
  if (from._internal_timestamp() != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  if (from._internal_isenter() != 0) {
    _this->_impl_.isenter_ = from._impl_.isenter_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReqUploadAppBehaviour::CopyFrom(const ReqUploadAppBehaviour& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lampyris.crypto.protocol.app.ReqUploadAppBehaviour)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReqUploadAppBehaviour::InternalSwap(ReqUploadAppBehaviour* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, &other->_impl_.symbol_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_.isenter_)
      + sizeof(ReqUploadAppBehaviour::_impl_.isenter_)
      - PROTOBUF_FIELD_OFFSET(ReqUploadAppBehaviour, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata ReqUploadAppBehaviour::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResNotice::_Internal {
 public:
};

ResNotice::ResNotice(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lampyris.crypto.protocol.app.ResNotice)
}
inline PROTOBUF_NDEBUG_INLINE ResNotice::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::lampyris::crypto::protocol::app::ResNotice& from_msg)
      : content_(arena, from.content_),
        _cached_size_{0} {}

ResNotice::ResNotice(
    ::google::protobuf::Arena* arena,
    const ResNotice& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResNotice* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:lampyris.crypto.protocol.app.ResNotice)
}
inline PROTOBUF_NDEBUG_INLINE ResNotice::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        _cached_size_{0} {}

inline void ResNotice::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
ResNotice::~ResNotice() {
  // @@protoc_insertion_point(destructor:lampyris.crypto.protocol.app.ResNotice)
  SharedDtor(*this);
}
inline void ResNotice::SharedDtor(MessageLite& self) {
  ResNotice& this_ = static_cast<ResNotice&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ResNotice::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ResNotice(arena);
}
constexpr auto ResNotice::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResNotice),
                                            alignof(ResNotice));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ResNotice::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ResNotice_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ResNotice::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ResNotice>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ResNotice::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ResNotice>(), &ResNotice::ByteSizeLong,
            &ResNotice::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ResNotice, _impl_._cached_size_),
        false,
    },
    &ResNotice::kDescriptorMethods,
    &descriptor_table_app_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ResNotice::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 54, 2> ResNotice::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::lampyris::crypto::protocol::app::ResNotice>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .lampyris.crypto.protocol.app.NoticeType type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResNotice, _impl_.type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ResNotice, _impl_.type_)}},
    // string content = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ResNotice, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string content = 1;
    {PROTOBUF_FIELD_OFFSET(ResNotice, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .lampyris.crypto.protocol.app.NoticeType type = 2;
    {PROTOBUF_FIELD_OFFSET(ResNotice, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\46\7\0\0\0\0\0\0"
    "lampyris.crypto.protocol.app.ResNotice"
    "content"
  }},
};

PROTOBUF_NOINLINE void ResNotice::Clear() {
// @@protoc_insertion_point(message_clear_start:lampyris.crypto.protocol.app.ResNotice)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _impl_.type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ResNotice::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ResNotice& this_ = static_cast<const ResNotice&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ResNotice::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ResNotice& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:lampyris.crypto.protocol.app.ResNotice)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string content = 1;
          if (!this_._internal_content().empty()) {
            const std::string& _s = this_._internal_content();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lampyris.crypto.protocol.app.ResNotice.content");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // .lampyris.crypto.protocol.app.NoticeType type = 2;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_type(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:lampyris.crypto.protocol.app.ResNotice)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ResNotice::ByteSizeLong(const MessageLite& base) {
          const ResNotice& this_ = static_cast<const ResNotice&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ResNotice::ByteSizeLong() const {
          const ResNotice& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:lampyris.crypto.protocol.app.ResNotice)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string content = 1;
            if (!this_._internal_content().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_content());
            }
            // .lampyris.crypto.protocol.app.NoticeType type = 2;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ResNotice::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResNotice*>(&to_msg);
  auto& from = static_cast<const ResNotice&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lampyris.crypto.protocol.app.ResNotice)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResNotice::CopyFrom(const ResNotice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lampyris.crypto.protocol.app.ResNotice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResNotice::InternalSwap(ResNotice* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
  swap(_impl_.type_, other->_impl_.type_);
}

::google::protobuf::Metadata ResNotice::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace app
}  // namespace protocol
}  // namespace crypto
}  // namespace lampyris
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_app_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
