// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: quote.proto
// Protobuf Java Version: 4.29.3

package lampyris.futu.protocol.quote;

public final class Quote {
  private Quote() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Quote.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuoteDataBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lampyris.futu.protocol.quote.QuoteDataBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>double price = 2;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>double changePerc = 3;</code>
     * @return The changePerc.
     */
    double getChangePerc();

    /**
     * <code>double riseSpeed = 4;</code>
     * @return The riseSpeed.
     */
    double getRiseSpeed();
  }
  /**
   * Protobuf type {@code lampyris.futu.protocol.quote.QuoteDataBean}
   */
  public static final class QuoteDataBean extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lampyris.futu.protocol.quote.QuoteDataBean)
      QuoteDataBeanOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        QuoteDataBean.class.getName());
    }
    // Use QuoteDataBean.newBuilder() to construct.
    private QuoteDataBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private QuoteDataBean() {
      symbol_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_QuoteDataBean_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_QuoteDataBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lampyris.futu.protocol.quote.Quote.QuoteDataBean.class, lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder.class);
    }

    public static final int SYMBOL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 1;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private double price_ = 0D;
    /**
     * <code>double price = 2;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }

    public static final int CHANGEPERC_FIELD_NUMBER = 3;
    private double changePerc_ = 0D;
    /**
     * <code>double changePerc = 3;</code>
     * @return The changePerc.
     */
    @java.lang.Override
    public double getChangePerc() {
      return changePerc_;
    }

    public static final int RISESPEED_FIELD_NUMBER = 4;
    private double riseSpeed_ = 0D;
    /**
     * <code>double riseSpeed = 4;</code>
     * @return The riseSpeed.
     */
    @java.lang.Override
    public double getRiseSpeed() {
      return riseSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, symbol_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        output.writeDouble(2, price_);
      }
      if (java.lang.Double.doubleToRawLongBits(changePerc_) != 0) {
        output.writeDouble(3, changePerc_);
      }
      if (java.lang.Double.doubleToRawLongBits(riseSpeed_) != 0) {
        output.writeDouble(4, riseSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, symbol_);
      }
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, price_);
      }
      if (java.lang.Double.doubleToRawLongBits(changePerc_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, changePerc_);
      }
      if (java.lang.Double.doubleToRawLongBits(riseSpeed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, riseSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lampyris.futu.protocol.quote.Quote.QuoteDataBean)) {
        return super.equals(obj);
      }
      lampyris.futu.protocol.quote.Quote.QuoteDataBean other = (lampyris.futu.protocol.quote.Quote.QuoteDataBean) obj;

      if (!getSymbol()
          .equals(other.getSymbol())) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (java.lang.Double.doubleToLongBits(getChangePerc())
          != java.lang.Double.doubleToLongBits(
              other.getChangePerc())) return false;
      if (java.lang.Double.doubleToLongBits(getRiseSpeed())
          != java.lang.Double.doubleToLongBits(
              other.getRiseSpeed())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + CHANGEPERC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getChangePerc()));
      hash = (37 * hash) + RISESPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRiseSpeed()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lampyris.futu.protocol.quote.Quote.QuoteDataBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lampyris.futu.protocol.quote.QuoteDataBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lampyris.futu.protocol.quote.QuoteDataBean)
        lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_QuoteDataBean_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_QuoteDataBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lampyris.futu.protocol.quote.Quote.QuoteDataBean.class, lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder.class);
      }

      // Construct using lampyris.futu.protocol.quote.Quote.QuoteDataBean.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        symbol_ = "";
        price_ = 0D;
        changePerc_ = 0D;
        riseSpeed_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_QuoteDataBean_descriptor;
      }

      @java.lang.Override
      public lampyris.futu.protocol.quote.Quote.QuoteDataBean getDefaultInstanceForType() {
        return lampyris.futu.protocol.quote.Quote.QuoteDataBean.getDefaultInstance();
      }

      @java.lang.Override
      public lampyris.futu.protocol.quote.Quote.QuoteDataBean build() {
        lampyris.futu.protocol.quote.Quote.QuoteDataBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lampyris.futu.protocol.quote.Quote.QuoteDataBean buildPartial() {
        lampyris.futu.protocol.quote.Quote.QuoteDataBean result = new lampyris.futu.protocol.quote.Quote.QuoteDataBean(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(lampyris.futu.protocol.quote.Quote.QuoteDataBean result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.symbol_ = symbol_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.changePerc_ = changePerc_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.riseSpeed_ = riseSpeed_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lampyris.futu.protocol.quote.Quote.QuoteDataBean) {
          return mergeFrom((lampyris.futu.protocol.quote.Quote.QuoteDataBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lampyris.futu.protocol.quote.Quote.QuoteDataBean other) {
        if (other == lampyris.futu.protocol.quote.Quote.QuoteDataBean.getDefaultInstance()) return this;
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getChangePerc() != 0D) {
          setChangePerc(other.getChangePerc());
        }
        if (other.getRiseSpeed() != 0D) {
          setRiseSpeed(other.getRiseSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                symbol_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 17: {
                price_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                changePerc_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                riseSpeed_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 1;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 1;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 1;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        symbol_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        symbol_ = getDefaultInstance().getSymbol();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 1;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        symbol_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 2;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 2;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {

        price_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        onChanged();
        return this;
      }

      private double changePerc_ ;
      /**
       * <code>double changePerc = 3;</code>
       * @return The changePerc.
       */
      @java.lang.Override
      public double getChangePerc() {
        return changePerc_;
      }
      /**
       * <code>double changePerc = 3;</code>
       * @param value The changePerc to set.
       * @return This builder for chaining.
       */
      public Builder setChangePerc(double value) {

        changePerc_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double changePerc = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChangePerc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        changePerc_ = 0D;
        onChanged();
        return this;
      }

      private double riseSpeed_ ;
      /**
       * <code>double riseSpeed = 4;</code>
       * @return The riseSpeed.
       */
      @java.lang.Override
      public double getRiseSpeed() {
        return riseSpeed_;
      }
      /**
       * <code>double riseSpeed = 4;</code>
       * @param value The riseSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setRiseSpeed(double value) {

        riseSpeed_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double riseSpeed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiseSpeed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        riseSpeed_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lampyris.futu.protocol.quote.QuoteDataBean)
    }

    // @@protoc_insertion_point(class_scope:lampyris.futu.protocol.quote.QuoteDataBean)
    private static final lampyris.futu.protocol.quote.Quote.QuoteDataBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lampyris.futu.protocol.quote.Quote.QuoteDataBean();
    }

    public static lampyris.futu.protocol.quote.Quote.QuoteDataBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuoteDataBean>
        PARSER = new com.google.protobuf.AbstractParser<QuoteDataBean>() {
      @java.lang.Override
      public QuoteDataBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QuoteDataBean> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuoteDataBean> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lampyris.futu.protocol.quote.Quote.QuoteDataBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResQuoteDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lampyris.futu.protocol.quote.ResQuoteData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    java.util.List<lampyris.futu.protocol.quote.Quote.QuoteDataBean> 
        getBeanListList();
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    lampyris.futu.protocol.quote.Quote.QuoteDataBean getBeanList(int index);
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    int getBeanListCount();
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    java.util.List<? extends lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder> 
        getBeanListOrBuilderList();
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder getBeanListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code lampyris.futu.protocol.quote.ResQuoteData}
   */
  public static final class ResQuoteData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lampyris.futu.protocol.quote.ResQuoteData)
      ResQuoteDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ResQuoteData.class.getName());
    }
    // Use ResQuoteData.newBuilder() to construct.
    private ResQuoteData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResQuoteData() {
      beanList_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_ResQuoteData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_ResQuoteData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lampyris.futu.protocol.quote.Quote.ResQuoteData.class, lampyris.futu.protocol.quote.Quote.ResQuoteData.Builder.class);
    }

    public static final int BEANLIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<lampyris.futu.protocol.quote.Quote.QuoteDataBean> beanList_;
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<lampyris.futu.protocol.quote.Quote.QuoteDataBean> getBeanListList() {
      return beanList_;
    }
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder> 
        getBeanListOrBuilderList() {
      return beanList_;
    }
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    @java.lang.Override
    public int getBeanListCount() {
      return beanList_.size();
    }
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    @java.lang.Override
    public lampyris.futu.protocol.quote.Quote.QuoteDataBean getBeanList(int index) {
      return beanList_.get(index);
    }
    /**
     * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
     */
    @java.lang.Override
    public lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder getBeanListOrBuilder(
        int index) {
      return beanList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < beanList_.size(); i++) {
        output.writeMessage(1, beanList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < beanList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, beanList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lampyris.futu.protocol.quote.Quote.ResQuoteData)) {
        return super.equals(obj);
      }
      lampyris.futu.protocol.quote.Quote.ResQuoteData other = (lampyris.futu.protocol.quote.Quote.ResQuoteData) obj;

      if (!getBeanListList()
          .equals(other.getBeanListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBeanListCount() > 0) {
        hash = (37 * hash) + BEANLIST_FIELD_NUMBER;
        hash = (53 * hash) + getBeanListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lampyris.futu.protocol.quote.Quote.ResQuoteData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lampyris.futu.protocol.quote.Quote.ResQuoteData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lampyris.futu.protocol.quote.ResQuoteData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lampyris.futu.protocol.quote.ResQuoteData)
        lampyris.futu.protocol.quote.Quote.ResQuoteDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_ResQuoteData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_ResQuoteData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lampyris.futu.protocol.quote.Quote.ResQuoteData.class, lampyris.futu.protocol.quote.Quote.ResQuoteData.Builder.class);
      }

      // Construct using lampyris.futu.protocol.quote.Quote.ResQuoteData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (beanListBuilder_ == null) {
          beanList_ = java.util.Collections.emptyList();
        } else {
          beanList_ = null;
          beanListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lampyris.futu.protocol.quote.Quote.internal_static_lampyris_futu_protocol_quote_ResQuoteData_descriptor;
      }

      @java.lang.Override
      public lampyris.futu.protocol.quote.Quote.ResQuoteData getDefaultInstanceForType() {
        return lampyris.futu.protocol.quote.Quote.ResQuoteData.getDefaultInstance();
      }

      @java.lang.Override
      public lampyris.futu.protocol.quote.Quote.ResQuoteData build() {
        lampyris.futu.protocol.quote.Quote.ResQuoteData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lampyris.futu.protocol.quote.Quote.ResQuoteData buildPartial() {
        lampyris.futu.protocol.quote.Quote.ResQuoteData result = new lampyris.futu.protocol.quote.Quote.ResQuoteData(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(lampyris.futu.protocol.quote.Quote.ResQuoteData result) {
        if (beanListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            beanList_ = java.util.Collections.unmodifiableList(beanList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.beanList_ = beanList_;
        } else {
          result.beanList_ = beanListBuilder_.build();
        }
      }

      private void buildPartial0(lampyris.futu.protocol.quote.Quote.ResQuoteData result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lampyris.futu.protocol.quote.Quote.ResQuoteData) {
          return mergeFrom((lampyris.futu.protocol.quote.Quote.ResQuoteData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lampyris.futu.protocol.quote.Quote.ResQuoteData other) {
        if (other == lampyris.futu.protocol.quote.Quote.ResQuoteData.getDefaultInstance()) return this;
        if (beanListBuilder_ == null) {
          if (!other.beanList_.isEmpty()) {
            if (beanList_.isEmpty()) {
              beanList_ = other.beanList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBeanListIsMutable();
              beanList_.addAll(other.beanList_);
            }
            onChanged();
          }
        } else {
          if (!other.beanList_.isEmpty()) {
            if (beanListBuilder_.isEmpty()) {
              beanListBuilder_.dispose();
              beanListBuilder_ = null;
              beanList_ = other.beanList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              beanListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBeanListFieldBuilder() : null;
            } else {
              beanListBuilder_.addAllMessages(other.beanList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                lampyris.futu.protocol.quote.Quote.QuoteDataBean m =
                    input.readMessage(
                        lampyris.futu.protocol.quote.Quote.QuoteDataBean.parser(),
                        extensionRegistry);
                if (beanListBuilder_ == null) {
                  ensureBeanListIsMutable();
                  beanList_.add(m);
                } else {
                  beanListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<lampyris.futu.protocol.quote.Quote.QuoteDataBean> beanList_ =
        java.util.Collections.emptyList();
      private void ensureBeanListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          beanList_ = new java.util.ArrayList<lampyris.futu.protocol.quote.Quote.QuoteDataBean>(beanList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          lampyris.futu.protocol.quote.Quote.QuoteDataBean, lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder, lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder> beanListBuilder_;

      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public java.util.List<lampyris.futu.protocol.quote.Quote.QuoteDataBean> getBeanListList() {
        if (beanListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(beanList_);
        } else {
          return beanListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public int getBeanListCount() {
        if (beanListBuilder_ == null) {
          return beanList_.size();
        } else {
          return beanListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public lampyris.futu.protocol.quote.Quote.QuoteDataBean getBeanList(int index) {
        if (beanListBuilder_ == null) {
          return beanList_.get(index);
        } else {
          return beanListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder setBeanList(
          int index, lampyris.futu.protocol.quote.Quote.QuoteDataBean value) {
        if (beanListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeanListIsMutable();
          beanList_.set(index, value);
          onChanged();
        } else {
          beanListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder setBeanList(
          int index, lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder builderForValue) {
        if (beanListBuilder_ == null) {
          ensureBeanListIsMutable();
          beanList_.set(index, builderForValue.build());
          onChanged();
        } else {
          beanListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder addBeanList(lampyris.futu.protocol.quote.Quote.QuoteDataBean value) {
        if (beanListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeanListIsMutable();
          beanList_.add(value);
          onChanged();
        } else {
          beanListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder addBeanList(
          int index, lampyris.futu.protocol.quote.Quote.QuoteDataBean value) {
        if (beanListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeanListIsMutable();
          beanList_.add(index, value);
          onChanged();
        } else {
          beanListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder addBeanList(
          lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder builderForValue) {
        if (beanListBuilder_ == null) {
          ensureBeanListIsMutable();
          beanList_.add(builderForValue.build());
          onChanged();
        } else {
          beanListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder addBeanList(
          int index, lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder builderForValue) {
        if (beanListBuilder_ == null) {
          ensureBeanListIsMutable();
          beanList_.add(index, builderForValue.build());
          onChanged();
        } else {
          beanListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder addAllBeanList(
          java.lang.Iterable<? extends lampyris.futu.protocol.quote.Quote.QuoteDataBean> values) {
        if (beanListBuilder_ == null) {
          ensureBeanListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, beanList_);
          onChanged();
        } else {
          beanListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder clearBeanList() {
        if (beanListBuilder_ == null) {
          beanList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          beanListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public Builder removeBeanList(int index) {
        if (beanListBuilder_ == null) {
          ensureBeanListIsMutable();
          beanList_.remove(index);
          onChanged();
        } else {
          beanListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder getBeanListBuilder(
          int index) {
        return getBeanListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder getBeanListOrBuilder(
          int index) {
        if (beanListBuilder_ == null) {
          return beanList_.get(index);  } else {
          return beanListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public java.util.List<? extends lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder> 
           getBeanListOrBuilderList() {
        if (beanListBuilder_ != null) {
          return beanListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(beanList_);
        }
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder addBeanListBuilder() {
        return getBeanListFieldBuilder().addBuilder(
            lampyris.futu.protocol.quote.Quote.QuoteDataBean.getDefaultInstance());
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder addBeanListBuilder(
          int index) {
        return getBeanListFieldBuilder().addBuilder(
            index, lampyris.futu.protocol.quote.Quote.QuoteDataBean.getDefaultInstance());
      }
      /**
       * <code>repeated .lampyris.futu.protocol.quote.QuoteDataBean beanList = 1;</code>
       */
      public java.util.List<lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder> 
           getBeanListBuilderList() {
        return getBeanListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          lampyris.futu.protocol.quote.Quote.QuoteDataBean, lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder, lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder> 
          getBeanListFieldBuilder() {
        if (beanListBuilder_ == null) {
          beanListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              lampyris.futu.protocol.quote.Quote.QuoteDataBean, lampyris.futu.protocol.quote.Quote.QuoteDataBean.Builder, lampyris.futu.protocol.quote.Quote.QuoteDataBeanOrBuilder>(
                  beanList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          beanList_ = null;
        }
        return beanListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:lampyris.futu.protocol.quote.ResQuoteData)
    }

    // @@protoc_insertion_point(class_scope:lampyris.futu.protocol.quote.ResQuoteData)
    private static final lampyris.futu.protocol.quote.Quote.ResQuoteData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lampyris.futu.protocol.quote.Quote.ResQuoteData();
    }

    public static lampyris.futu.protocol.quote.Quote.ResQuoteData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResQuoteData>
        PARSER = new com.google.protobuf.AbstractParser<ResQuoteData>() {
      @java.lang.Override
      public ResQuoteData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResQuoteData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResQuoteData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lampyris.futu.protocol.quote.Quote.ResQuoteData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lampyris_futu_protocol_quote_QuoteDataBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lampyris_futu_protocol_quote_QuoteDataBean_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lampyris_futu_protocol_quote_ResQuoteData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lampyris_futu_protocol_quote_ResQuoteData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013quote.proto\022\034lampyris.futu.protocol.qu" +
      "ote\"U\n\rQuoteDataBean\022\016\n\006symbol\030\001 \001(\t\022\r\n\005" +
      "price\030\002 \001(\001\022\022\n\nchangePerc\030\003 \001(\001\022\021\n\triseS" +
      "peed\030\004 \001(\001\"M\n\014ResQuoteData\022=\n\010beanList\030\001" +
      " \003(\0132+.lampyris.futu.protocol.quote.Quot" +
      "eDataBeanb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_lampyris_futu_protocol_quote_QuoteDataBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lampyris_futu_protocol_quote_QuoteDataBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lampyris_futu_protocol_quote_QuoteDataBean_descriptor,
        new java.lang.String[] { "Symbol", "Price", "ChangePerc", "RiseSpeed", });
    internal_static_lampyris_futu_protocol_quote_ResQuoteData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lampyris_futu_protocol_quote_ResQuoteData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lampyris_futu_protocol_quote_ResQuoteData_descriptor,
        new java.lang.String[] { "BeanList", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
