// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: app.proto
// Protobuf C++ Version: 5.29.3

#ifndef app_2eproto_2epb_2eh
#define app_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_app_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_app_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_app_2eproto;
namespace lampyris {
namespace crypto {
namespace protocol {
namespace app {
class ReqHeartBeat;
struct ReqHeartBeatDefaultTypeInternal;
extern ReqHeartBeatDefaultTypeInternal _ReqHeartBeat_default_instance_;
class ReqServerLogQuery;
struct ReqServerLogQueryDefaultTypeInternal;
extern ReqServerLogQueryDefaultTypeInternal _ReqServerLogQuery_default_instance_;
class ResClientMessage;
struct ResClientMessageDefaultTypeInternal;
extern ResClientMessageDefaultTypeInternal _ResClientMessage_default_instance_;
class ResHeartBeat;
struct ResHeartBeatDefaultTypeInternal;
extern ResHeartBeatDefaultTypeInternal _ResHeartBeat_default_instance_;
class ResServerLogPush;
struct ResServerLogPushDefaultTypeInternal;
extern ResServerLogPushDefaultTypeInternal _ResServerLogPush_default_instance_;
class ResServerLogQuery;
struct ResServerLogQueryDefaultTypeInternal;
extern ResServerLogQueryDefaultTypeInternal _ResServerLogQuery_default_instance_;
}  // namespace app
}  // namespace protocol
}  // namespace crypto
}  // namespace lampyris
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace lampyris {
namespace crypto {
namespace protocol {
namespace app {

// ===================================================================


// -------------------------------------------------------------------

class ResServerLogQuery final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lampyris.crypto.protocol.app.ResServerLogQuery) */ {
 public:
  inline ResServerLogQuery() : ResServerLogQuery(nullptr) {}
  ~ResServerLogQuery() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ResServerLogQuery* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ResServerLogQuery));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ResServerLogQuery(
      ::google::protobuf::internal::ConstantInitialized);

  inline ResServerLogQuery(const ResServerLogQuery& from) : ResServerLogQuery(nullptr, from) {}
  inline ResServerLogQuery(ResServerLogQuery&& from) noexcept
      : ResServerLogQuery(nullptr, std::move(from)) {}
  inline ResServerLogQuery& operator=(const ResServerLogQuery& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResServerLogQuery& operator=(ResServerLogQuery&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResServerLogQuery& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResServerLogQuery* internal_default_instance() {
    return reinterpret_cast<const ResServerLogQuery*>(
        &_ResServerLogQuery_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(ResServerLogQuery& a, ResServerLogQuery& b) { a.Swap(&b); }
  inline void Swap(ResServerLogQuery* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResServerLogQuery* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResServerLogQuery* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ResServerLogQuery>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResServerLogQuery& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ResServerLogQuery& from) { ResServerLogQuery::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ResServerLogQuery* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "lampyris.crypto.protocol.app.ResServerLogQuery"; }

 protected:
  explicit ResServerLogQuery(::google::protobuf::Arena* arena);
  ResServerLogQuery(::google::protobuf::Arena* arena, const ResServerLogQuery& from);
  ResServerLogQuery(::google::protobuf::Arena* arena, ResServerLogQuery&& from) noexcept
      : ResServerLogQuery(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLogListFieldNumber = 3,
    kStartIndexFieldNumber = 1,
    kEndIndexFieldNumber = 2,
  };
  // repeated string logList = 3;
  int loglist_size() const;
  private:
  int _internal_loglist_size() const;

  public:
  void clear_loglist() ;
  const std::string& loglist(int index) const;
  std::string* mutable_loglist(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_loglist(int index, Arg_&& value, Args_... args);
  std::string* add_loglist();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_loglist(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& loglist() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_loglist();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_loglist() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_loglist();

  public:
  // int32 startIndex = 1;
  void clear_startindex() ;
  ::int32_t startindex() const;
  void set_startindex(::int32_t value);

  private:
  ::int32_t _internal_startindex() const;
  void _internal_set_startindex(::int32_t value);

  public:
  // int32 endIndex = 2;
  void clear_endindex() ;
  ::int32_t endindex() const;
  void set_endindex(::int32_t value);

  private:
  ::int32_t _internal_endindex() const;
  void _internal_set_endindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:lampyris.crypto.protocol.app.ResServerLogQuery)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      62, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ResServerLogQuery& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> loglist_;
    ::int32_t startindex_;
    ::int32_t endindex_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_app_2eproto;
};
// -------------------------------------------------------------------

class ResServerLogPush final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lampyris.crypto.protocol.app.ResServerLogPush) */ {
 public:
  inline ResServerLogPush() : ResServerLogPush(nullptr) {}
  ~ResServerLogPush() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ResServerLogPush* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ResServerLogPush));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ResServerLogPush(
      ::google::protobuf::internal::ConstantInitialized);

  inline ResServerLogPush(const ResServerLogPush& from) : ResServerLogPush(nullptr, from) {}
  inline ResServerLogPush(ResServerLogPush&& from) noexcept
      : ResServerLogPush(nullptr, std::move(from)) {}
  inline ResServerLogPush& operator=(const ResServerLogPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResServerLogPush& operator=(ResServerLogPush&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResServerLogPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResServerLogPush* internal_default_instance() {
    return reinterpret_cast<const ResServerLogPush*>(
        &_ResServerLogPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(ResServerLogPush& a, ResServerLogPush& b) { a.Swap(&b); }
  inline void Swap(ResServerLogPush* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResServerLogPush* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResServerLogPush* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ResServerLogPush>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResServerLogPush& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ResServerLogPush& from) { ResServerLogPush::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ResServerLogPush* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "lampyris.crypto.protocol.app.ResServerLogPush"; }

 protected:
  explicit ResServerLogPush(::google::protobuf::Arena* arena);
  ResServerLogPush(::google::protobuf::Arena* arena, const ResServerLogPush& from);
  ResServerLogPush(::google::protobuf::Arena* arena, ResServerLogPush&& from) noexcept
      : ResServerLogPush(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLogFieldNumber = 2,
    kIndexFieldNumber = 1,
  };
  // string log = 2;
  void clear_log() ;
  const std::string& log() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_log(Arg_&& arg, Args_... args);
  std::string* mutable_log();
  PROTOBUF_NODISCARD std::string* release_log();
  void set_allocated_log(std::string* value);

  private:
  const std::string& _internal_log() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_log(
      const std::string& value);
  std::string* _internal_mutable_log();

  public:
  // int32 index = 1;
  void clear_index() ;
  ::int32_t index() const;
  void set_index(::int32_t value);

  private:
  ::int32_t _internal_index() const;
  void _internal_set_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:lampyris.crypto.protocol.app.ResServerLogPush)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      57, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ResServerLogPush& from_msg);
    ::google::protobuf::internal::ArenaStringPtr log_;
    ::int32_t index_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_app_2eproto;
};
// -------------------------------------------------------------------

class ResHeartBeat final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lampyris.crypto.protocol.app.ResHeartBeat) */ {
 public:
  inline ResHeartBeat() : ResHeartBeat(nullptr) {}
  ~ResHeartBeat() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ResHeartBeat* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ResHeartBeat));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ResHeartBeat(
      ::google::protobuf::internal::ConstantInitialized);

  inline ResHeartBeat(const ResHeartBeat& from) : ResHeartBeat(nullptr, from) {}
  inline ResHeartBeat(ResHeartBeat&& from) noexcept
      : ResHeartBeat(nullptr, std::move(from)) {}
  inline ResHeartBeat& operator=(const ResHeartBeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResHeartBeat& operator=(ResHeartBeat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResHeartBeat& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResHeartBeat* internal_default_instance() {
    return reinterpret_cast<const ResHeartBeat*>(
        &_ResHeartBeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ResHeartBeat& a, ResHeartBeat& b) { a.Swap(&b); }
  inline void Swap(ResHeartBeat* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResHeartBeat* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResHeartBeat* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ResHeartBeat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResHeartBeat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ResHeartBeat& from) { ResHeartBeat::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ResHeartBeat* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "lampyris.crypto.protocol.app.ResHeartBeat"; }

 protected:
  explicit ResHeartBeat(::google::protobuf::Arena* arena);
  ResHeartBeat(::google::protobuf::Arena* arena, const ResHeartBeat& from);
  ResHeartBeat(::google::protobuf::Arena* arena, ResHeartBeat&& from) noexcept
      : ResHeartBeat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServerTimeFieldNumber = 1,
  };
  // int64 serverTime = 1;
  void clear_servertime() ;
  ::int64_t servertime() const;
  void set_servertime(::int64_t value);

  private:
  ::int64_t _internal_servertime() const;
  void _internal_set_servertime(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:lampyris.crypto.protocol.app.ResHeartBeat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ResHeartBeat& from_msg);
    ::int64_t servertime_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_app_2eproto;
};
// -------------------------------------------------------------------

class ResClientMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lampyris.crypto.protocol.app.ResClientMessage) */ {
 public:
  inline ResClientMessage() : ResClientMessage(nullptr) {}
  ~ResClientMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ResClientMessage* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ResClientMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ResClientMessage(
      ::google::protobuf::internal::ConstantInitialized);

  inline ResClientMessage(const ResClientMessage& from) : ResClientMessage(nullptr, from) {}
  inline ResClientMessage(ResClientMessage&& from) noexcept
      : ResClientMessage(nullptr, std::move(from)) {}
  inline ResClientMessage& operator=(const ResClientMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResClientMessage& operator=(ResClientMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResClientMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResClientMessage* internal_default_instance() {
    return reinterpret_cast<const ResClientMessage*>(
        &_ResClientMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ResClientMessage& a, ResClientMessage& b) { a.Swap(&b); }
  inline void Swap(ResClientMessage* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResClientMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResClientMessage* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ResClientMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ResClientMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ResClientMessage& from) { ResClientMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ResClientMessage* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "lampyris.crypto.protocol.app.ResClientMessage"; }

 protected:
  explicit ResClientMessage(::google::protobuf::Arena* arena);
  ResClientMessage(::google::protobuf::Arena* arena, const ResClientMessage& from);
  ResClientMessage(::google::protobuf::Arena* arena, ResClientMessage&& from) noexcept
      : ResClientMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kContentFieldNumber = 1,
    kParamFieldNumber = 3,
    kMessageTypeFieldNumber = 2,
  };
  // string content = 1;
  void clear_content() ;
  const std::string& content() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_content(Arg_&& arg, Args_... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* value);

  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(
      const std::string& value);
  std::string* _internal_mutable_content();

  public:
  // optional string param = 3;
  bool has_param() const;
  void clear_param() ;
  const std::string& param() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_param(Arg_&& arg, Args_... args);
  std::string* mutable_param();
  PROTOBUF_NODISCARD std::string* release_param();
  void set_allocated_param(std::string* value);

  private:
  const std::string& _internal_param() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_param(
      const std::string& value);
  std::string* _internal_mutable_param();

  public:
  // int32 messageType = 2;
  void clear_messagetype() ;
  ::int32_t messagetype() const;
  void set_messagetype(::int32_t value);

  private:
  ::int32_t _internal_messagetype() const;
  void _internal_set_messagetype(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:lampyris.crypto.protocol.app.ResClientMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      66, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ResClientMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr content_;
    ::google::protobuf::internal::ArenaStringPtr param_;
    ::int32_t messagetype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_app_2eproto;
};
// -------------------------------------------------------------------

class ReqServerLogQuery final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lampyris.crypto.protocol.app.ReqServerLogQuery) */ {
 public:
  inline ReqServerLogQuery() : ReqServerLogQuery(nullptr) {}
  ~ReqServerLogQuery() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReqServerLogQuery* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReqServerLogQuery));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReqServerLogQuery(
      ::google::protobuf::internal::ConstantInitialized);

  inline ReqServerLogQuery(const ReqServerLogQuery& from) : ReqServerLogQuery(nullptr, from) {}
  inline ReqServerLogQuery(ReqServerLogQuery&& from) noexcept
      : ReqServerLogQuery(nullptr, std::move(from)) {}
  inline ReqServerLogQuery& operator=(const ReqServerLogQuery& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqServerLogQuery& operator=(ReqServerLogQuery&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqServerLogQuery& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqServerLogQuery* internal_default_instance() {
    return reinterpret_cast<const ReqServerLogQuery*>(
        &_ReqServerLogQuery_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ReqServerLogQuery& a, ReqServerLogQuery& b) { a.Swap(&b); }
  inline void Swap(ReqServerLogQuery* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqServerLogQuery* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqServerLogQuery* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReqServerLogQuery>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReqServerLogQuery& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReqServerLogQuery& from) { ReqServerLogQuery::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReqServerLogQuery* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "lampyris.crypto.protocol.app.ReqServerLogQuery"; }

 protected:
  explicit ReqServerLogQuery(::google::protobuf::Arena* arena);
  ReqServerLogQuery(::google::protobuf::Arena* arena, const ReqServerLogQuery& from);
  ReqServerLogQuery(::google::protobuf::Arena* arena, ReqServerLogQuery&& from) noexcept
      : ReqServerLogQuery(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStartIndexFieldNumber = 1,
    kEndIndexFieldNumber = 2,
  };
  // optional int32 startIndex = 1;
  bool has_startindex() const;
  void clear_startindex() ;
  ::int32_t startindex() const;
  void set_startindex(::int32_t value);

  private:
  ::int32_t _internal_startindex() const;
  void _internal_set_startindex(::int32_t value);

  public:
  // optional int32 endIndex = 2;
  bool has_endindex() const;
  void clear_endindex() ;
  ::int32_t endindex() const;
  void set_endindex(::int32_t value);

  private:
  ::int32_t _internal_endindex() const;
  void _internal_set_endindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:lampyris.crypto.protocol.app.ReqServerLogQuery)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ReqServerLogQuery& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t startindex_;
    ::int32_t endindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_app_2eproto;
};
// -------------------------------------------------------------------

class ReqHeartBeat final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:lampyris.crypto.protocol.app.ReqHeartBeat) */ {
 public:
  inline ReqHeartBeat() : ReqHeartBeat(nullptr) {}
  ~ReqHeartBeat() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReqHeartBeat* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReqHeartBeat));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReqHeartBeat(
      ::google::protobuf::internal::ConstantInitialized);

  inline ReqHeartBeat(const ReqHeartBeat& from) : ReqHeartBeat(nullptr, from) {}
  inline ReqHeartBeat(ReqHeartBeat&& from) noexcept
      : ReqHeartBeat(nullptr, std::move(from)) {}
  inline ReqHeartBeat& operator=(const ReqHeartBeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqHeartBeat& operator=(ReqHeartBeat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqHeartBeat& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqHeartBeat* internal_default_instance() {
    return reinterpret_cast<const ReqHeartBeat*>(
        &_ReqHeartBeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ReqHeartBeat& a, ReqHeartBeat& b) { a.Swap(&b); }
  inline void Swap(ReqHeartBeat* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqHeartBeat* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqHeartBeat* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReqHeartBeat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReqHeartBeat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReqHeartBeat& from) { ReqHeartBeat::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReqHeartBeat* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "lampyris.crypto.protocol.app.ReqHeartBeat"; }

 protected:
  explicit ReqHeartBeat(::google::protobuf::Arena* arena);
  ReqHeartBeat(::google::protobuf::Arena* arena, const ReqHeartBeat& from);
  ReqHeartBeat(::google::protobuf::Arena* arena, ReqHeartBeat&& from) noexcept
      : ReqHeartBeat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClientTimeFieldNumber = 1,
    kIsForegroundFieldNumber = 2,
  };
  // int64 clientTime = 1;
  void clear_clienttime() ;
  ::int64_t clienttime() const;
  void set_clienttime(::int64_t value);

  private:
  ::int64_t _internal_clienttime() const;
  void _internal_set_clienttime(::int64_t value);

  public:
  // bool isForeground = 2;
  void clear_isforeground() ;
  bool isforeground() const;
  void set_isforeground(bool value);

  private:
  bool _internal_isforeground() const;
  void _internal_set_isforeground(bool value);

  public:
  // @@protoc_insertion_point(class_scope:lampyris.crypto.protocol.app.ReqHeartBeat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ReqHeartBeat& from_msg);
    ::int64_t clienttime_;
    bool isforeground_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_app_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ReqHeartBeat

// int64 clientTime = 1;
inline void ReqHeartBeat::clear_clienttime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clienttime_ = ::int64_t{0};
}
inline ::int64_t ReqHeartBeat::clienttime() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ReqHeartBeat.clientTime)
  return _internal_clienttime();
}
inline void ReqHeartBeat::set_clienttime(::int64_t value) {
  _internal_set_clienttime(value);
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ReqHeartBeat.clientTime)
}
inline ::int64_t ReqHeartBeat::_internal_clienttime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clienttime_;
}
inline void ReqHeartBeat::_internal_set_clienttime(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clienttime_ = value;
}

// bool isForeground = 2;
inline void ReqHeartBeat::clear_isforeground() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isforeground_ = false;
}
inline bool ReqHeartBeat::isforeground() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ReqHeartBeat.isForeground)
  return _internal_isforeground();
}
inline void ReqHeartBeat::set_isforeground(bool value) {
  _internal_set_isforeground(value);
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ReqHeartBeat.isForeground)
}
inline bool ReqHeartBeat::_internal_isforeground() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isforeground_;
}
inline void ReqHeartBeat::_internal_set_isforeground(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isforeground_ = value;
}

// -------------------------------------------------------------------

// ResHeartBeat

// int64 serverTime = 1;
inline void ResHeartBeat::clear_servertime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servertime_ = ::int64_t{0};
}
inline ::int64_t ResHeartBeat::servertime() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResHeartBeat.serverTime)
  return _internal_servertime();
}
inline void ResHeartBeat::set_servertime(::int64_t value) {
  _internal_set_servertime(value);
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResHeartBeat.serverTime)
}
inline ::int64_t ResHeartBeat::_internal_servertime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.servertime_;
}
inline void ResHeartBeat::_internal_set_servertime(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.servertime_ = value;
}

// -------------------------------------------------------------------

// ResClientMessage

// string content = 1;
inline void ResClientMessage::clear_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.ClearToEmpty();
}
inline const std::string& ResClientMessage::content() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResClientMessage.content)
  return _internal_content();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ResClientMessage::set_content(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResClientMessage.content)
}
inline std::string* ResClientMessage::mutable_content() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:lampyris.crypto.protocol.app.ResClientMessage.content)
  return _s;
}
inline const std::string& ResClientMessage::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.content_.Get();
}
inline void ResClientMessage::_internal_set_content(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.Set(value, GetArena());
}
inline std::string* ResClientMessage::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.content_.Mutable( GetArena());
}
inline std::string* ResClientMessage::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lampyris.crypto.protocol.app.ResClientMessage.content)
  return _impl_.content_.Release();
}
inline void ResClientMessage::set_allocated_content(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:lampyris.crypto.protocol.app.ResClientMessage.content)
}

// int32 messageType = 2;
inline void ResClientMessage::clear_messagetype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.messagetype_ = 0;
}
inline ::int32_t ResClientMessage::messagetype() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResClientMessage.messageType)
  return _internal_messagetype();
}
inline void ResClientMessage::set_messagetype(::int32_t value) {
  _internal_set_messagetype(value);
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResClientMessage.messageType)
}
inline ::int32_t ResClientMessage::_internal_messagetype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.messagetype_;
}
inline void ResClientMessage::_internal_set_messagetype(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.messagetype_ = value;
}

// optional string param = 3;
inline bool ResClientMessage::has_param() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ResClientMessage::clear_param() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.param_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ResClientMessage::param() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResClientMessage.param)
  return _internal_param();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ResClientMessage::set_param(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.param_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResClientMessage.param)
}
inline std::string* ResClientMessage::mutable_param() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_param();
  // @@protoc_insertion_point(field_mutable:lampyris.crypto.protocol.app.ResClientMessage.param)
  return _s;
}
inline const std::string& ResClientMessage::_internal_param() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.param_.Get();
}
inline void ResClientMessage::_internal_set_param(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.param_.Set(value, GetArena());
}
inline std::string* ResClientMessage::_internal_mutable_param() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.param_.Mutable( GetArena());
}
inline std::string* ResClientMessage::release_param() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lampyris.crypto.protocol.app.ResClientMessage.param)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.param_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.param_.Set("", GetArena());
  }
  return released;
}
inline void ResClientMessage::set_allocated_param(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.param_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.param_.IsDefault()) {
    _impl_.param_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:lampyris.crypto.protocol.app.ResClientMessage.param)
}

// -------------------------------------------------------------------

// ReqServerLogQuery

// optional int32 startIndex = 1;
inline bool ReqServerLogQuery::has_startindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ReqServerLogQuery::clear_startindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t ReqServerLogQuery::startindex() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ReqServerLogQuery.startIndex)
  return _internal_startindex();
}
inline void ReqServerLogQuery::set_startindex(::int32_t value) {
  _internal_set_startindex(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ReqServerLogQuery.startIndex)
}
inline ::int32_t ReqServerLogQuery::_internal_startindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.startindex_;
}
inline void ReqServerLogQuery::_internal_set_startindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startindex_ = value;
}

// optional int32 endIndex = 2;
inline bool ReqServerLogQuery::has_endindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ReqServerLogQuery::clear_endindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.endindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t ReqServerLogQuery::endindex() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ReqServerLogQuery.endIndex)
  return _internal_endindex();
}
inline void ReqServerLogQuery::set_endindex(::int32_t value) {
  _internal_set_endindex(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ReqServerLogQuery.endIndex)
}
inline ::int32_t ReqServerLogQuery::_internal_endindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.endindex_;
}
inline void ReqServerLogQuery::_internal_set_endindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.endindex_ = value;
}

// -------------------------------------------------------------------

// ResServerLogQuery

// int32 startIndex = 1;
inline void ResServerLogQuery::clear_startindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startindex_ = 0;
}
inline ::int32_t ResServerLogQuery::startindex() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResServerLogQuery.startIndex)
  return _internal_startindex();
}
inline void ResServerLogQuery::set_startindex(::int32_t value) {
  _internal_set_startindex(value);
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResServerLogQuery.startIndex)
}
inline ::int32_t ResServerLogQuery::_internal_startindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.startindex_;
}
inline void ResServerLogQuery::_internal_set_startindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.startindex_ = value;
}

// int32 endIndex = 2;
inline void ResServerLogQuery::clear_endindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.endindex_ = 0;
}
inline ::int32_t ResServerLogQuery::endindex() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResServerLogQuery.endIndex)
  return _internal_endindex();
}
inline void ResServerLogQuery::set_endindex(::int32_t value) {
  _internal_set_endindex(value);
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResServerLogQuery.endIndex)
}
inline ::int32_t ResServerLogQuery::_internal_endindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.endindex_;
}
inline void ResServerLogQuery::_internal_set_endindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.endindex_ = value;
}

// repeated string logList = 3;
inline int ResServerLogQuery::_internal_loglist_size() const {
  return _internal_loglist().size();
}
inline int ResServerLogQuery::loglist_size() const {
  return _internal_loglist_size();
}
inline void ResServerLogQuery::clear_loglist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.loglist_.Clear();
}
inline std::string* ResServerLogQuery::add_loglist() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_loglist()->Add();
  // @@protoc_insertion_point(field_add_mutable:lampyris.crypto.protocol.app.ResServerLogQuery.logList)
  return _s;
}
inline const std::string& ResServerLogQuery::loglist(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResServerLogQuery.logList)
  return _internal_loglist().Get(index);
}
inline std::string* ResServerLogQuery::mutable_loglist(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:lampyris.crypto.protocol.app.ResServerLogQuery.logList)
  return _internal_mutable_loglist()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ResServerLogQuery::set_loglist(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_loglist()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResServerLogQuery.logList)
}
template <typename Arg_, typename... Args_>
inline void ResServerLogQuery::add_loglist(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_loglist(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:lampyris.crypto.protocol.app.ResServerLogQuery.logList)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ResServerLogQuery::loglist() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:lampyris.crypto.protocol.app.ResServerLogQuery.logList)
  return _internal_loglist();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ResServerLogQuery::mutable_loglist() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:lampyris.crypto.protocol.app.ResServerLogQuery.logList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_loglist();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ResServerLogQuery::_internal_loglist() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.loglist_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ResServerLogQuery::_internal_mutable_loglist() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.loglist_;
}

// -------------------------------------------------------------------

// ResServerLogPush

// int32 index = 1;
inline void ResServerLogPush::clear_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.index_ = 0;
}
inline ::int32_t ResServerLogPush::index() const {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResServerLogPush.index)
  return _internal_index();
}
inline void ResServerLogPush::set_index(::int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResServerLogPush.index)
}
inline ::int32_t ResServerLogPush::_internal_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.index_;
}
inline void ResServerLogPush::_internal_set_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.index_ = value;
}

// string log = 2;
inline void ResServerLogPush::clear_log() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_.ClearToEmpty();
}
inline const std::string& ResServerLogPush::log() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:lampyris.crypto.protocol.app.ResServerLogPush.log)
  return _internal_log();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ResServerLogPush::set_log(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:lampyris.crypto.protocol.app.ResServerLogPush.log)
}
inline std::string* ResServerLogPush::mutable_log() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_log();
  // @@protoc_insertion_point(field_mutable:lampyris.crypto.protocol.app.ResServerLogPush.log)
  return _s;
}
inline const std::string& ResServerLogPush::_internal_log() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.log_.Get();
}
inline void ResServerLogPush::_internal_set_log(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_.Set(value, GetArena());
}
inline std::string* ResServerLogPush::_internal_mutable_log() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.log_.Mutable( GetArena());
}
inline std::string* ResServerLogPush::release_log() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:lampyris.crypto.protocol.app.ResServerLogPush.log)
  return _impl_.log_.Release();
}
inline void ResServerLogPush::set_allocated_log(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.log_.IsDefault()) {
    _impl_.log_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:lampyris.crypto.protocol.app.ResServerLogPush.log)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace app
}  // namespace protocol
}  // namespace crypto
}  // namespace lampyris


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // app_2eproto_2epb_2eh
